---
sidebar: sidebar 
permalink: legal-notices_noinclude.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais. 
---
= Avisos legais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais.



== Direitos de autor

http://www.netapp.com/us/legal/copyright.aspx[]



== Marcas comerciais

NetApp, o logotipo DA NetApp e as marcas listadas na página de marcas comerciais da NetApp são marcas comerciais da NetApp, Inc. Outros nomes de produtos e empresas podem ser marcas comerciais de seus respetivos proprietários.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Patentes

Uma lista atual de patentes de propriedade da NetApp pode ser encontrada em:

https://www.netapp.com/us/media/patents-page.pdf[]



== Política de privacidade

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Licença de API Astra Control

https://docs.netapp.com/us-en/astra-automation-2204/media/astra-api-license.pdf[]



== Código aberto

Os arquivos de aviso fornecem informações sobre direitos autorais de terceiros e licenças usadas no software NetApp.

link:NOTICE_AstraCloudControl_21.08.pdf["Aviso para a versão Astra Control Center 21,08"^]
